[package]
name = "discord-backup-util"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
ureq = "2.10.1"
zip = { version = "2.2.0", features = ["aes", "deflate-zlib"] }
