name: Publish

on:
  push:
    branches: [ "stable" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: ningenMe/setup-rustup@v1.1.0
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: musl-tools mold gcc-mingw-w64 gcc-multilib llvm-lib gcc-mingw-w64-x86-64
        version: 1.0
    - run: cargo install cargo-xwin --locked

    - name: Create release dir
      run: rm -fr target/github-release && mkdir -p target/github-release
    
    - name: Install x86_64-unknown-linux-gnu toolchain
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Build for x86_64-unknown-linux-gnu
      run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
    - name: Copy x86_64-unknown-linux-gnu artifact
      run: cp target/x86_64-unknown-linux-gnu/release/discord-backup-util target/github-release/discord-backup-util.x86_64-unknown-linux-gnu
      
    - name: Install x86_64-unknown-linux-musl toolchain
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build for x86_64-unknown-linux-gnu
      run: cargo build --verbose --release --target x86_64-unknown-linux-musl
    - name: Copy x86_64-unknown-linux-musl artifact
      run: cp target/x86_64-unknown-linux-musl/release/discord-backup-util target/github-release/discord-backup-util.x86_64-unknown-linux-musl
      
    - name: Install i586-unknown-linux-gnu toolchain
      run: rustup target add i586-unknown-linux-gnu
    - name: Build for i586-unknown-linux-gnu
      run: cargo build --verbose --release --target i586-unknown-linux-gnu --no-default-features --features minreq
    - name: Copy i586-unknown-linux-gnu artifact
      run: cp target/i586-unknown-linux-gnu/release/discord-backup-util target/github-release/discord-backup-util.i586-unknown-linux-gnu
      
    - name: Install i686-unknown-linux-gnu toolchain
      run: rustup target add i686-unknown-linux-gnu
    - name: Build for i686-unknown-linux-gnu
      run: cargo build --verbose --release --target i686-unknown-linux-gnu
    - name: Copy i686-unknown-linux-gnu artifact
      run: cp target/i686-unknown-linux-gnu/release/discord-backup-util target/github-release/discord-backup-util.i686-unknown-linux-gnu

    - name: Install x86_64-pc-windows-gnu toolchain
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build for x86_64-pc-windows-gnu
      run: cargo build --verbose --release --target x86_64-pc-windows-gnu
    - name: Copy x86_64-pc-windows-gnu artifact
      run: cp target/x86_64-pc-windows-gnu/release/discord-backup-util.exe target/github-release/discord-backup-util.x86_64-pc-windows-gnu.exe

    - name: Install x86_64-pc-windows-msvc toolchain
      run: rustup target add x86_64-pc-windows-msvc
    - name: Build for x86_64-pc-windows-msvc
      run: cargo xwin build --verbose --release --target x86_64-pc-windows-msvc
    - name: Copy x86_64-pc-windows-msvc artifact
      run: cp target/x86_64-pc-windows-msvc/release/discord-backup-util.exe target/github-release/discord-backup-util.x86_64-pc-windows-msvc.exe
      
    - uses: colathro/crate-version@1.0.0
      id: crate-version
      with:
        file: Cargo.toml
    - uses: ncipollo/release-action@v1
      with:
        tag: v${{ steps.crate-version.outputs.version }}
        artifacts: "target/github-release/*"
        commit: stable
        generateReleaseNotes: true
